language: cpp
os: linux
compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - ./InstallPackagesUbuntu.sh

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
    - os: linux
      sudo: required
      dist: xenial

script: make